apiVersion: v2
appVersion: "1.0"
description: ZeeQS Helm Chart for Kubernetes
name: zeebe-zeeqs-helm
version: 0.1.1-SNAPSHOT
icon: https://zeebe.io/img/zeebe-logo.png
dependencies:
- name: hazelcast
  repository: https://hazelcast-charts.s3.amazonaws.com/
  version: 3.5.0
  condition: "hazelcast.enabled"